import type { OnboardingSummary } from '../types';

/**
 * DeepSeek AI Service (Backend Proxy Version)
 * Powering agentic AI features via secure Netlify Functions
 */
export const deepSeekService = {
    /**
     * Generates project analysis by calling the secure backend
     */
    generateProjectAnalysis: async (summary: OnboardingSummary): Promise<string> => {
        try {
            const response = await fetch('/.netlify/functions/deepseek-agent', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    type: 'analysis',
                    summary
                })
            });

            if (!response.ok) {
                const error = await response.json();
                throw new Error(error.error || 'DeepSeek Backend connection failed');
            }

            const data = await response.json();
            return data.choices[0].message.content;
        } catch (error: any) {
            console.error('Secure DeepSeek Analysis Error:', error);
            throw error;
        }
    },

    /**
     * Generates resource estimation by calling the secure backend
     */
    generateCostEstimation: async (summary: OnboardingSummary): Promise<{
        minBudget: number;
        maxBudget: number;
        estimatedHours: number;
        rationale: string;
        currency: string;
    }> => {
        try {
            const response = await fetch('/.netlify/functions/deepseek-agent', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    type: 'estimation',
                    summary
                })
            });

            if (!response.ok) {
                const error = await response.json();
                throw new Error(error.error || 'DeepSeek Estimation Backend connection failed');
            }

            const data = await response.json();
            const content = JSON.parse(data.choices[0].message.content);
            return {
                minBudget: content.minBudget || 0,
                maxBudget: content.maxBudget || 0,
                estimatedHours: content.estimatedHours || 0,
                rationale: content.rationale || 'Estimation generated by AI strategist.',
                currency: content.currency || 'USD'
            };
        } catch (error: any) {
            console.error('Secure Estimation Error:', error);
            throw error;
        }
    },

    /**
     * Handles chat interactions with the AI strategist
     */
    chatWithStrategist: async (summary: OnboardingSummary, messages: { role: 'user' | 'assistant'; content: string }[]): Promise<string> => {
        try {
            const response = await fetch('/.netlify/functions/deepseek-agent', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    type: 'chat',
                    summary,
                    messages
                })
            });

            if (!response.ok) {
                const error = await response.json();
                throw new Error(error.error || 'DeepSeek Chat connection failed');
            }

            const data = await response.json();
            return data.choices[0].message.content;
        } catch (error: any) {
            console.error('Secure Chat Error:', error);
            throw error;
        }
    }
};
