import type { OnboardingSummary } from '../types';

/**
 * Service to handle email formatting and generation
 */
export const emailService = {
    /**
     * Generates a mailto link for the onboarding summary
     */
    generateMailtoLink: (summary: OnboardingSummary, recipientType: 'client' | 'team'): string => {
        const subject = `Project Discovery Summary: ${summary.clientInfo.company} - ${summary.projectInfo.serviceName}`;
        const recipient = recipientType === 'client' ? summary.clientInfo.email : 'team@youragency.com';

        let body = `Hello ${recipientType === 'client' ? summary.clientInfo.name : 'Team'},\n\n`;

        if (recipientType === 'client') {
            body += `It was a pleasure conducting the AI-guided discovery for your upcoming project. Based on our session, we've compiled a strategic roadmap to ensure your project's success.\n\n`;
        } else {
            body += `🔥 NEW PROJECT OPPORTUNITY: ${summary.clientInfo.company}\n`;
            body += `An AI-guided discovery session has just been completed. Actions are required to initiate the kickoff phase.\n\n`;
        }

        body += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
        body += `📊 STRATEGIC OVERVIEW\n`;
        body += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
        body += `🏢 Client:   ${summary.clientInfo.company}\n`;
        body += `🛠️ Service:  ${summary.projectInfo.serviceName}\n`;
        body += `⏳ Timeline: ${summary.projectInfo.constraints.timeline}\n`;
        body += `💰 Budget:   ${summary.projectInfo.constraints.budget}\n\n`;

        body += `🎯 PRIMARY OBJECTIVES\n`;
        summary.projectInfo.goals.forEach(goal => {
            body += `• ${goal}\n`;
        });
        body += `\n`;

        if (summary.identifiedRisks.length > 0) {
            body += `⚠️ STRATEGIC CONSIDERATIONS\n`;
            summary.identifiedRisks.forEach(risk => {
                body += `[${risk.severity.toUpperCase()}] ${risk.category}: ${risk.description}\n`;
            });
            body += `\n`;
        }

        body += `🚀 NEXT STEPS & MILESTONES\n`;
        summary.nextSteps.forEach(step => {
            body += `→ ${step}\n`;
        });

        body += `\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
        body += `This report was autonomously generated by the AI Onboarding Agent.\n`;
        body += `Kind Regards,\nAI Production Team @ Agency`;

        return `mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    }
};
