import React, { useMemo, useEffect } from 'react';
import confetti from 'canvas-confetti';
import type { OnboardingSummary, ClickUpSyncResult } from '../types';
import { clickUpService } from '../services/clickUpService';
import { emailService } from '../utils/emailService';
import { aiAgencyBrain } from '../utils/aiAgencyBrain';
import { deepSeekService } from '../services/deepSeekService';
import './SummaryView.css';

interface SummaryViewProps {
    summary: OnboardingSummary;
    onBack: () => void;
}

const SummaryView: React.FC<SummaryViewProps> = ({ summary, onBack }) => {
    const [syncStatus, setSyncStatus] = React.useState<{ loading: boolean; result?: ClickUpSyncResult }>({ loading: false });
    const [aiReport, setAiReport] = React.useState<{ loading: boolean; content?: string }>({ loading: false });
    const [estimation, setEstimation] = React.useState<{
        loading: boolean;
        data?: { minBudget: number; maxBudget: number; estimatedHours: number; rationale: string; currency: string }
    }>({ loading: false });

    useEffect(() => {
        // Trigger celebration
        const duration = 3 * 1000;
        const animationEnd = Date.now() + duration;
        const defaults = { startVelocity: 30, spread: 360, ticks: 60, zIndex: 0 };

        const randomInRange = (min: number, max: number) => Math.random() * (max - min) + min;

        const interval: any = setInterval(function () {
            const timeLeft = animationEnd - Date.now();

            if (timeLeft <= 0) {
                return clearInterval(interval);
            }

            const particleCount = 50 * (timeLeft / duration);
            confetti({
                ...defaults,
                particleCount,
                origin: { x: randomInRange(0.1, 0.3), y: Math.random() - 0.2 }
            });
            confetti({
                ...defaults,
                particleCount,
                origin: { x: randomInRange(0.7, 0.9), y: Math.random() - 0.2 }
            });
        }, 250);

        return () => clearInterval(interval);
    }, []);

    // Agentic AI Analysis (Local Baseline)
    const aiAnalysis = useMemo(() => aiAgencyBrain.analyzeProject(summary), [summary]);

    const handleGenerateAiReport = async () => {
        setAiReport({ loading: true });
        try {
            const content = await deepSeekService.generateProjectAnalysis(summary);
            setAiReport({ loading: false, content });
        } catch (e) {
            setAiReport({ loading: false });
            alert('AI Error: Please ensure backend API Keys are configured on Netlify.');
        }
    };

    const handleGenerateEstimation = async () => {
        setEstimation({ loading: true });
        try {
            const data = await deepSeekService.generateCostEstimation(summary);
            setEstimation({ loading: false, data });
        } catch (e) {
            setEstimation({ loading: false });
            alert('Estimation Error: Please ensure backend API Keys are configured on Netlify.');
        }
    };

    const handleSyncToClickUp = async () => {
        setSyncStatus({ loading: true });
        const result = await clickUpService.syncToClickUp(summary);
        setSyncStatus({ loading: false, result });
    };

    const handleEmailSummary = () => {
        window.location.href = emailService.generateMailtoLink(summary, 'client');
    };

    return (
        <div className="summary-view container container-md fade-in">
            <div className="summary-header">
                <div className="ai-badge">✨ AI Optimized Strategy</div>
                <h1>Project Intelligence Summary</h1>
                <p className="session-info">Generated by AI Agent • {new Date().toLocaleDateString()}</p>
            </div>

            <div className="bento-grid">
                {/* Confidence & Readiness */}
                <div className="bento-item bento-lg glass-card insights-card">
                    <div className="meter-header">
                        <span className="info-label">Kickoff Readiness</span>
                        <span className="ai-badge" style={{ background: aiAnalysis.confidenceScore > 70 ? 'var(--color-success)' : 'var(--color-warning)' }}>
                            {aiAnalysis.readinessLabel}
                        </span>
                    </div>
                    <div className="progress-bar">
                        <div
                            className="progress-bar-fill"
                            style={{ width: `${aiAnalysis.confidenceScore}%`, background: 'var(--color-accent)' }}
                        ></div>
                    </div>
                    <p className="help-text" style={{ marginTop: '15px' }}>
                        Our AI has analyzed your requirements and determined a {aiAnalysis.confidenceScore}% clarity score for immediate project kickoff.
                    </p>
                </div>

                <div className="bento-item bento-md glass-card" style={{ background: 'linear-gradient(135deg, rgba(34, 197, 94, 0.05), rgba(16, 185, 129, 0.05))' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' }}>
                        <h3>💰 AI Cost Estimation</h3>
                        <button
                            className={`btn btn-primary ${estimation.loading ? 'loading' : ''}`}
                            style={{ padding: '6px 12px', fontSize: '11px', background: 'var(--color-success)' }}
                            onClick={handleGenerateEstimation}
                            disabled={estimation.loading}
                        >
                            {estimation.loading ? 'Calculating...' : estimation.data ? 'Recalculate' : 'Generate Estimate'}
                        </button>
                    </div>

                    {estimation.data ? (
                        <div className="fade-in">
                            <div style={{ display: 'flex', gap: '20px', marginBottom: '15px' }}>
                                <div>
                                    <span className="info-label">Budget Range</span>
                                    <h4 style={{ color: 'var(--color-success)' }}>
                                        {estimation.data.minBudget.toLocaleString()} - {estimation.data.maxBudget.toLocaleString()} {estimation.data.currency}
                                    </h4>
                                </div>
                                <div>
                                    <span className="info-label">Est. Hours</span>
                                    <h4>{estimation.data.estimatedHours} hrs</h4>
                                </div>
                            </div>
                            <p className="help-text" style={{ fontSize: '12px', paddingTop: '10px' }}>
                                💡 {estimation.data.rationale}
                            </p>
                        </div>
                    ) : (
                        <p className="help-text">Click to generate a budget and resource estimation based on scope.</p>
                    )}
                </div>

                <div className="bento-item bento-md glass-card text-center">
                    <span className="info-label">Project Type</span>
                    <h3 style={{ margin: '10px 0' }}>{summary.projectInfo.serviceName}</h3>
                    <div className="ai-badge" style={{ fontSize: '10px' }}>Priority Level: High</div>
                </div>

                {/* Strategic Insights */}
                <div className="bento-item bento-full glass-card">
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
                        <h3>🧠 Strategic AI Insights</h3>
                        <button
                            className={`btn btn-primary ${aiReport.loading ? 'loading' : ''}`}
                            style={{ padding: '8px 16px', fontSize: '12px' }}
                            onClick={handleGenerateAiReport}
                            disabled={aiReport.loading}
                        >
                            {aiReport.loading ? 'Agent Thinking...' : aiReport.content ? 'Regenerate Analysis' : 'Generate DeepSeek Report'}
                        </button>
                    </div>

                    {aiReport.content ? (
                        <div className="ai-report-content fade-in" style={{
                            padding: '20px',
                            background: 'rgba(0,0,0,0.2)',
                            borderRadius: '12px',
                            lineHeight: '1.6',
                            color: 'var(--color-text-secondary)',
                            maxHeight: '400px',
                            overflowY: 'auto'
                        }}>
                            <div dangerouslySetInnerHTML={{ __html: aiReport.content.replace(/\n/g, '<br/>') }} />
                        </div>
                    ) : (
                        <div className="insights-list" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '20px' }}>
                            {aiAnalysis.strategicInsights.map((insight, i) => (
                                <div key={i} className="risk-item">
                                    <div className="risk-badge" style={{ background: 'var(--color-bg-tertiary)', color: 'var(--color-accent)', border: '1px solid var(--color-accent)' }}>
                                        {insight.type.toUpperCase()}
                                    </div>
                                    <h4 style={{ margin: '5px 0' }}>{insight.title}</h4>
                                    <p className="risk-desc" style={{ fontSize: 'var(--font-size-sm)' }}>{insight.description}</p>
                                </div>
                            ))}
                        </div>
                    )}
                </div>

                {/* Client & Scope */}
                <div className="bento-item bento-md glass-card">
                    <h3>Client Profile</h3>
                    <div className="info-grid">
                        <div className="info-item">
                            <span className="info-label">Company</span>
                            <span className="info-value">{summary.clientInfo.company || 'N/A'}</span>
                        </div>
                        <div className="info-item">
                            <span className="info-label">Industry</span>
                            <span className="info-value">{summary.clientInfo.industry || 'N/A'}</span>
                        </div>
                    </div>
                </div>

                <div className="bento-item bento-md glass-card">
                    <h3>Budget & Timeline</h3>
                    <div className="info-grid">
                        <div className="info-item">
                            <span className="info-label">Timeline</span>
                            <span className="info-value">{summary.projectInfo.constraints.timeline}</span>
                        </div>
                        <div className="info-item">
                            <span className="info-label">Budget</span>
                            <span className="info-value">{summary.projectInfo.constraints.budget}</span>
                        </div>
                    </div>
                </div>

                {/* Upsell / Growth Add-ons */}
                <div className="bento-item bento-full glass-card insights-card">
                    <h3 className="text-gradient">Recommended Growth Add-ons</h3>
                    <div className="checkbox-grid" style={{ marginTop: '15px' }}>
                        {aiAnalysis.suggestedAddons.map((addon, i) => (
                            <div key={i} className="checkbox-card" style={{ cursor: 'default', background: 'rgba(255,255,255,0.03)' }}>
                                <span>✨ {addon}</span>
                            </div>
                        ))}
                        {aiAnalysis.suggestedAddons.length === 0 && <p className="help-text">Standard requirements are optimized.</p>}
                    </div>
                </div>
            </div>

            <div className="summary-actions">
                {syncStatus.result?.success ? (
                    <div className="sync-success glass-card slide-in">
                        <p>✅ Successfully synced to ClickUp!</p>
                        <a href={syncStatus.result.taskUrl} target="_blank" rel="noopener noreferrer" className="btn btn-outline">
                            View Task in ClickUp
                        </a>
                    </div>
                ) : (
                    <div className="action-group">
                        <button
                            className={`btn btn-primary ${syncStatus.loading ? 'loading' : ''}`}
                            onClick={handleSyncToClickUp}
                            disabled={syncStatus.loading}
                        >
                            {syncStatus.loading ? 'Syncing...' : 'Sync to ClickUp'}
                        </button>
                        {syncStatus.result?.error && (
                            <p className="error-message">{syncStatus.result.error}</p>
                        )}
                    </div>
                )}

                <div className="secondary-actions">
                    <button className="btn btn-outline" onClick={handleEmailSummary}>
                        ✉️ Email Summary
                    </button>
                    <button className="btn btn-outline" onClick={() => window.print()}>
                        📄 Print / Save PDF
                    </button>
                    <button className="btn btn-secondary" onClick={onBack}>
                        Exit Discovery
                    </button>
                </div>
            </div>
        </div>
    );
};

export default SummaryView;
